---
- name: Add Nginx Repo
  apt_repository:
    repo: ppa:nginx/stable
    state: present

- name: Install Nginx
  apt:
    name: nginx
    state: installed
    update_cache: true
  notify:
    - Start Nginx

- name: Add H5BP Config
  copy:
    src: h5bp
    dest: /etc/nginx
    owner: root
    group: root

- name: Disable Default Site Config
  file:
    dest: /etc/nginx/sites-enables/default
    state: absent

- name: Create Web Root
  file:
    path: '{{ domain }}'
    mode: 775
    state: directory
    owner: www-data
    group: www-data
  notify:
    - Reload Nginx

- name: Web Root Permissions
  file:
    dest: '/var/www/{{ domain }}'
    mode: 775
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
  notify:
    - Reload Nginx